In [113]:
import numpy as np
class TransportationProblem(object):
    def __init__(self, I,J):
        # The grid is I by J
        self.I = I
        self.J = J
        self.grid=np.ones((I,J))
    def set_avoids(self,items):
        #needs list of lists to avoid ex. ((1,4),(3,4),(4,2))
        for item in items:
            i=item[0]
            j=item[1]
            self.grid[i,j]=1000
        return 
    def random_populate(self):
        self.grid= np.random.rand(self.I,self.J)
        return
    def startState(self):
        return (0,0)
    def isEnd(self, state):
        return state == (self.I-1,self.J-1)
    def succAndCost(self, state):
        # return a list of (action, newState, cost) triples, takes a list of current potion (x,y)
        result = []
        if state[1]+1<self.J and state[0]>=0 and state[1]>=0:
            result.append(('right', (state[0],state[1]+1), self.grid[state[0],state[1]+1]))
        if state[0]+1<self.I  and state[0]>=0 and state[1]>=0:
            result.append(('down', (state[0]+1,state[1]), self.grid[state[0]+1,state[1]]))
        return result
def dynamicProgramming(problem):
    # state -> futureCost
    cache = {}
    def futureCost(state):
        # return best cost of reaching the end from state
        if problem.isEnd(state):
            return 0
        if state in cache:
            return cache[state][0]



        result = min([(cost+futureCost(newState),action,newState, cost) for action, newState, cost in problem.succAndCost(state)])
        #result = min([cost+futureCost(newState) for action, newState, cost in problem.succAndCost(state)])
        cache[state] = result
        return result[0]
    # recover total cost
    totalCost = futureCost(problem.startState())
    # recover history
    history = []
    state = problem.startState()
    while not problem.isEnd(state):
        #print(cache)
        _, action, newState, cost = cache[state]
        history.append((action, newState, cost))
        state = newState
    
    return (totalCost, history)
def printSolution(solution):
    totalCost, history = solution
    print('Total cost: {}'.format(totalCost))
    for step in history:
        print(step)



In [102]:
cache={(7, 8): 1.0, (6, 8): 2.0, (5, 8): 3.0, (4, 8): 4.0, (3, 8): 5.0, (2, 8): 6.0, (1, 8): 7.0, (0, 8): 8.0, (8, 7): 1.0, (7, 7): 2.0, (6, 7): 3.0, (5, 7): 4.0, (4, 7): 5.0, (3, 7): 6.0, (2, 7): 7.0, (1, 7): 8.0, (0, 7): 9.0, (8, 6): 2.0, (7, 6): 1002.0, (6, 6): 4.0, (5, 6): 5.0, (4, 6): 6.0, (3, 6): 7.0, (2, 6): 8.0, (1, 6): 9.0, (0, 6): 10.0, (8, 5): 1002.0, (7, 5): 1003.0, (6, 5): 5.0, (5, 5): 6.0, (4, 5): 7.0, (3, 5): 8.0, (2, 5): 9.0, (1, 5): 10.0, (0, 5): 11.0, (8, 4): 1003.0, (7, 4): 1004.0, (6, 4): 6.0, (5, 4): 7.0, (4, 4): 8.0, (3, 4): 9.0, (2, 4): 10.0, (1, 4): 11.0, (0, 4): 12.0, (8, 3): 1004.0, (7, 3): 1005.0, (6, 3): 7.0, (5, 3): 8.0, (4, 3): 9.0, (3, 3): 1009.0, (2, 3): 11.0, (1, 3): 12.0, (0, 3): 13.0, (8, 2): 1005.0, (7, 2): 1006.0, (6, 2): 8.0, (5, 2): 9.0, (4, 2): 10.0, (3, 2): 1010.0, (2, 2): 12.0, (1, 2): 13.0, (0, 2): 14.0, (8, 1): 1006.0, (7, 1): 1007.0, (6, 1): 9.0, (5, 1): 10.0, (4, 1): 11.0, (3, 1): 12.0, (2, 1): 13.0, (1, 1): 14.0, (0, 1): 15.0, (8, 0): 1007.0, (7, 0): 1008.0, (6, 0): 10.0, (5, 0): 11.0, (4, 0): 12.0, (3, 0): 13.0, (2, 0): 14.0, (1, 0): 15.0, (0, 0): 16.0}
cache[(7, 8)]

1.0

In [106]:
problem.succAndCost((4, 4))

[('right', (4, 5), 1.0), ('down', (5, 4), 1.0)]

In [114]:
problem=TransportationProblem(9,9)
problem.set_avoids(((1,4),(3,4),(4,2),(4,3),(7,7),(8,6),(7,7),(8,6)))
print(problem.grid)
#print(problem.succAndCost((7,7)))
printSolution(dynamicProgramming(problem))


[[   1.    1.    1.    1.    1.    1.    1.    1.    1.]
 [   1.    1.    1.    1. 1000.    1.    1.    1.    1.]
 [   1.    1.    1.    1.    1.    1.    1.    1.    1.]
 [   1.    1.    1.    1. 1000.    1.    1.    1.    1.]
 [   1.    1. 1000. 1000.    1.    1.    1.    1.    1.]
 [   1.    1.    1.    1.    1.    1.    1.    1.    1.]
 [   1.    1.    1.    1.    1.    1.    1.    1.    1.]
 [   1.    1.    1.    1.    1.    1.    1. 1000.    1.]
 [   1.    1.    1.    1.    1.    1. 1000.    1.    1.]]
Total cost: 16.0
('down', (1, 0), 1.0)
('down', (2, 0), 1.0)
('down', (3, 0), 1.0)
('down', (4, 0), 1.0)
('down', (5, 0), 1.0)
('down', (6, 0), 1.0)
('right', (6, 1), 1.0)
('right', (6, 2), 1.0)
('right', (6, 3), 1.0)
('right', (6, 4), 1.0)
('right', (6, 5), 1.0)
('right', (6, 6), 1.0)
('right', (6, 7), 1.0)
('right', (6, 8), 1.0)
('down', (7, 8), 1.0)
('down', (8, 8), 1.0)


In [115]:
problem=TransportationProblem(3,2)
problem.random_populate()
print(problem.grid)
printSolution(dynamicProgramming(problem))

[[0.04628951 0.19425208]
 [0.04321919 0.20842675]
 [0.98781162 0.52723019]]
Total cost: 0.778876128626858
('down', (1, 0), 0.04321919469791091)
('right', (1, 1), 0.20842674629486557)
('down', (2, 1), 0.5272301876340815)
